pipeline:
  name: Build vending-machine-api
  identifier: Build_vending_machine_api_1688065353671
  projectIdentifier: testdemo
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Install project dependecies
                  identifier: Install_project_dependecies
                  spec:
                    connectorRef: cipherdockerconnector
                    image: node
                    shell: Sh
                    command: npm install
                isContainerStepGroup: false
              - step:
                  type: Run
                  name: Build project
                  identifier: Echo_Welcome_Message
                  spec:
                    connectorRef: cipherdockerconnector
                    image: node
                    shell: Sh
                    command: npm run build
                  description: Build project
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and push image to docker
                  identifier: Build_and_push_image_to_docker
                  spec:
                    connectorRef: <+input>
                    repo: <+input>
                    tags:
                      - latetest
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1688065297428
        repoName: victormazeli/vending-machine-api
        build: <+input>
